### PR TITLE
Cors: isCorsRequest() and isPreflightRequest() made public + tests

### PR DESCRIPTION
**Pull request by MacDada**
https://github.com/jdesrosiers/silex-cors-provider/issues/22

### CODE REVIEW

**Comment by jdesrosiers** [comment]
I don't think this is right solution.  I think the filter functionality and the CORS functionality need to be extracted into different classes.  The filter class would call the CORS class.  That would allow you access to the functions you need without giving behavior to the filter class that doesn't involve the filter.  This design decision has been bothering me for a while.  I knew at some point something like this would come up.

**Comment by MacDada** [comment]
>  I think the filter functionality and the CORS functionality need to be extracted into different classes.

i totally agree, but wasn't sure if this is a right time for larger refactorings ;)

**Comment by jdesrosiers** [comment]
It's always a good time for refactorings!

**Comment by jdesrosiers** [comment]
Closing this pull request because we are taking another approach.  See #24

**Pull request closed without merging**
